const UPDATE_LIST_CHAIR_CHOSEN_CURRENT = 'bookingTicket/UPDATE_LIST_CHAIR_CHOSEN_CURRENT'
const UPDATE_STATUS_CHAIR = 'bookingTicket/UPDATE_STATUS_CHAIR'
const PAYMENT = "bookingTicket/PAYMENT"

export { UPDATE_LIST_CHAIR_CHOSEN_CURRENT, UPDATE_STATUS_CHAIR, PAYMENT }